//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/GameProto.proto
namespace FSD.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameLoginReq")]
  public partial class GameLoginReq : global::ProtoBuf.IExtensible
  {
    public GameLoginReq() {}
    
    private uint _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}